# =============================================================================
# Staging Environment Values
# =============================================================================
# These values override defaults for staging deployments.
# =============================================================================

backend:
  replicaCount: 1
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  autoscaling:
    enabled: false

  env:
    DEBUG: "true"

frontend:
  replicaCount: 1

  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"

  autoscaling:
    enabled: false

ingress:
  enabled: true
  className: nginx
  host: staging.orbit.example.com  # Override this!
  
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  
  tls:
    enabled: true
    secretName: orbit-staging-tls

postgresql:
  enabled: true
  primary:
    persistence:
      size: 5Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

podDisruptionBudget:
  enabled: false
