# =============================================================================
# Production Environment Values
# =============================================================================
# These values override defaults for production deployments.
#
# Database Configuration:
# -----------------------
# For cloud deployments (GKE/EKS with Terraform), use external database.
# The database is provisioned by Terraform and connection info is available
# via Terraform outputs. Create a Kubernetes secret with the database password:
#
#   kubectl create secret generic orbit-db-secret \
#     --namespace orbit-production \
#     --from-literal=password=$(terraform output -raw database_password)
#
# Then uncomment the externalDatabase section below and set postgresql.enabled: false
# =============================================================================

backend:
  replicaCount: 2
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  env:
    DEBUG: "false"

frontend:
  replicaCount: 2

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: nginx
  host: orbit.example.com  # Override this!
  
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  
  tls:
    enabled: true
    secretName: orbit-tls

# -----------------------------------------------------------------------------
# Database Configuration
# -----------------------------------------------------------------------------
# Option 1: Use in-cluster PostgreSQL (default for simple deployments)
postgresql:
  enabled: true
  primary:
    persistence:
      size: 20Gi
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1000m"

# Option 2: Use external database (Cloud SQL/RDS provisioned by Terraform)
# Uncomment below and set postgresql.enabled: false
# externalDatabase:
#   enabled: true
#   host: ""      # Set from: terraform output database_host
#   port: 5432
#   database: ""  # Set from: terraform output database_name
#   username: ""  # Set from: terraform output database_user
#   existingSecret: "orbit-db-secret"
#   existingSecretPasswordKey: "password"

podDisruptionBudget:
  enabled: true
  minAvailable: 1
