# =============================================================================
# Staging Environment Values
# =============================================================================
# These values override defaults for staging deployments.
#
# Database Configuration:
# -----------------------
# For cloud deployments (GKE/EKS with Terraform), use external database.
# The database is provisioned by Terraform and connection info is available
# via Terraform outputs. Create a Kubernetes secret with the database password:
#
#   kubectl create secret generic orbit-db-secret \
#     --namespace orbit-staging \
#     --from-literal=password=$(terraform output -raw database_password)
#
# Then uncomment the externalDatabase section below and set postgresql.enabled: false
# =============================================================================

backend:
  replicaCount: 1
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  autoscaling:
    enabled: false

  env:
    DEBUG: "true"

frontend:
  replicaCount: 1

  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"

  autoscaling:
    enabled: false

ingress:
  enabled: true
  className: nginx
  host: staging.orbit.example.com  # Override this!
  
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  
  tls:
    enabled: true
    secretName: orbit-staging-tls

# -----------------------------------------------------------------------------
# Database Configuration
# -----------------------------------------------------------------------------
# Option 1: Use in-cluster PostgreSQL (default for simple deployments)
postgresql:
  enabled: true
  primary:
    persistence:
      size: 5Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# Option 2: Use external database (Cloud SQL/RDS provisioned by Terraform)
# Uncomment below and set postgresql.enabled: false
# externalDatabase:
#   enabled: true
#   host: ""      # Set from: terraform output database_host
#   port: 5432
#   database: ""  # Set from: terraform output database_name
#   username: ""  # Set from: terraform output database_user
#   existingSecret: "orbit-db-secret"
#   existingSecretPasswordKey: "password"

podDisruptionBudget:
  enabled: false
